// <auto-generated />
namespace GoogleMap.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mahmut2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mahmut2));
        
        string IMigrationMetadata.Id
        {
            get { return "201512311004310_Mahmut2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
